[db]
data-source = "postgresql://postgres.qrwadtuuhhzbhckeyhbl:Barabanki1@12@aws-0-ap-south-1.pooler.supabase.com:6543/postgres"
prepare-stmt = false
log-level = "info"

[server]
port = 8080
read-timeout = "1h"
write-timeout = "1h"
graceful-shutdown = "10s"

[db.pool]
enable = true
max-open-connections = 25
max-idle-connections = 10
max-lifetime = "10m"

[jwt]
allowed-users = ["koobla007"]
secret = "3d83b297fefe647451cfaf07503e1ef4"
session-time = "720h" 

[tg]
pool-size = 16
rate = 200
rate-burst = 10
ntp = true
disable-stream-bots = false
storage-file = ''
proxy = ''
rate-limit = true
reconnect-timeout = '5m'

[tg.stream]
buffers = 16
chunk-timeout = '30s'

[tg.uploads]
multi-threads = 4
encryption-key = ''
max-retries = 10
retention = '7d'
threads = '16'

[log]
level = "info"